name: Deploy photo app
on:
  push:
    branches:
    - main

jobs:
  create-envfile:

    runs-on: ubuntu-latest

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
        directory: './'
        file_name: .env
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v18.14.1
      uses: actions/setup-node@v4
      with:
          node-version: v18.14.1
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env: 
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-3' # optional: defaults to us-east-1
        SOURCE_DIR: 'dist'